# Generated by Django 6.0.5 on 2026-05-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenciaNFe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave_acesso', models.CharField(max_length=50, unique=True, verbose_name='Chave de Acesso')),
                ('numero_nota', models.CharField(max_length=20, verbose_name='Número da Nota')),
                ('fornecedor', models.CharField(max_length=200, verbose_name='Fornecedor (Emitente)')),
                ('cnpj_fornecedor', models.CharField(max_length=20, verbose_name='CNPJ do Fornecedor')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('data_conferencia', models.DateTimeField(verbose_name='Data/Hora da Conferência')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data do Upload')),
            ],
            options={
                'verbose_name': 'Conferência de NFe',
                'verbose_name_plural': 'Conferências de NFe',
                'ordering': ['-data_conferencia'],
            },
        ),
    ]
