# Generated by Django 6.0.5 on 2026-05-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencianfe',
            name='dados_completos',
            field=models.JSONField(blank=True, null=True, verbose_name='Dados Completos da NFe'),
        ),
    ]
